# Generated by Django 3.1.7 on 2021-03-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_auto_20210304_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breastcancer',
            name='diagnosis',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='breastcancer',
            name='id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
