# Generated by Django 3.1.7 on 2021-03-05 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0004_auto_20210305_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcancer',
            name='fractal_dimension_worst',
        ),
        migrations.RemoveField(
            model_name='traincancer',
            name='fractal_dimension_worst',
        ),
    ]
