# Generated by Django 3.1.7 on 2021-03-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0005_auto_20210305_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcancer',
            name='id',
            field=models.IntegerField(max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='traincancer',
            name='id',
            field=models.IntegerField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
