# Generated by Django 3.1.7 on 2021-03-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0007_auto_20210305_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eps', models.FloatField()),
                ('pri', models.FloatField()),
            ],
        ),
    ]
