# Generated by Django 3.1.7 on 2021-03-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0008_surveyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShapleyInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('shapley', models.FloatField()),
            ],
        ),
    ]
