# Generated by Django 3.1.7 on 2021-03-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0009_shapleyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataset', models.CharField(max_length=256)),
                ('coverage', models.FloatField()),
                ('price', models.FloatField()),
                ('epsilon', models.FloatField()),
                ('state', models.IntegerField()),
            ],
        ),
    ]
