# Generated by Django 3.1.7 on 2021-03-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0010_modelinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestIris',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sepallength', models.FloatField()),
                ('sepalwidth', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainIris',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sepallength', models.FloatField()),
                ('sepalwidth', models.FloatField()),
            ],
        ),
    ]
