# Generated by Django 3.1.7 on 2021-03-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0011_testiris_trainiris'),
    ]

    operations = [
        migrations.AddField(
            model_name='testiris',
            name='label',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trainiris',
            name='label',
            field=models.IntegerField(default=1),
        ),
    ]
