# Generated by Django 3.1.7 on 2021-07-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0012_auto_20210313_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapleyinfo',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
