# Generated by Django 3.1.7 on 2021-07-05 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0014_auto_20210705_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shapleyinfo',
            name='compensation',
        ),
    ]
